# Generated by Django 6.0.7 on 2026-09-20 09:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Antigravity ID Platform', max_length=150)),
                ('platform_logo', models.ImageField(blank=True, null=True, upload_to='platform/branding/')),
                ('support_email', models.EmailField(default='support@idplatform.io', max_length=254)),
                ('support_phone', models.CharField(default='+1-800-ID-CARDS', max_length=50)),
                ('default_trial_days', models.PositiveIntegerField(default=30)),
                ('default_subscription_months', models.PositiveIntegerField(default=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_students', models.PositiveIntegerField(default=500, help_text='Maximum students allowed under this tier')),
                ('max_staff', models.PositiveIntegerField(default=50, help_text='Maximum staff/teachers allowed under this tier')),
                ('price_per_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_per_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, editable=False, help_text='Immutable unique organization code (e.g. ORG-00001)', max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('org_type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('TRAINING_INSTITUTE', 'Training Institute'), ('COMPANY', 'Company / Corporate'), ('NGO', 'NGO / Non-Profit'), ('OTHER', 'Other Institution')], default='SCHOOL', max_length=30)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_organizations', to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_profile', to='core.school')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ORG_CREATED', 'Organization Created'), ('ORG_UPDATED', 'Organization Updated'), ('ORG_SUSPENDED', 'Organization Suspended'), ('ORG_ACTIVATED', 'Organization Activated'), ('PLAN_CHANGED', 'Subscription Plan Changed'), ('SUBSCRIPTION_EXTENDED', 'Subscription Extended'), ('ADMIN_CREATED', 'Organization Admin Created'), ('ADMIN_PASSWORD_RESET', 'Admin Password Reset'), ('USER_STATUS_TOGGLED', 'User Status Changed'), ('SUPPORT_MODE_ENTERED', 'Support Mode Entered'), ('SUPPORT_MODE_EXITED', 'Support Mode Exited'), ('SETTINGS_UPDATED', 'Platform Settings Updated')], db_index=True, max_length=60)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='platform_admin.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal super-admin notes, billing details, contract refs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='platform_admin.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='platform_admin.subscriptionplan')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to='platform_admin.organization')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
