# Generated by Django 6.0.7 on 2026-09-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='app_contact_email',
            field=models.EmailField(blank=True, default='support@apexid.io', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_contact_phone',
            field=models.CharField(blank=True, default='+977-9800000000', max_length=50, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_copyright_text',
            field=models.CharField(blank=True, default='2026', max_length=150, verbose_name='Copyright Text / Year'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_description',
            field=models.TextField(blank=True, default='A school student ID-card management and verification application.', verbose_name='Mobile App Description'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_designer_name',
            field=models.CharField(blank=True, default='Apex Software Systems', max_length=150, verbose_name='Developer / Designer Name'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_designer_role',
            field=models.CharField(blank=True, default='Designer & Developer', max_length=150, verbose_name='Developer Role'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='platform/mobile_app/', verbose_name='Mobile App Logo'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_name',
            field=models.CharField(default='Apex ID - Teacher Portal', max_length=150, verbose_name='Mobile App Name'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_version',
            field=models.CharField(default='1.0.0', max_length=50, verbose_name='Mobile App Version'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='app_website',
            field=models.URLField(blank=True, default='https://apexid.io', verbose_name='Official Website'),
        ),
    ]
