# Generated by Django 6.0.7 on 2026-09-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('platform_admin', '0002_platformsetting_app_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_clients',
            field=models.PositiveIntegerField(default=1, help_text='Maximum client schools/companies managed under this tier (1 for school, 5-50+ for studio/press)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('TRAINING_INSTITUTE', 'Training Institute'), ('COMPANY', 'Company / Corporate'), ('STUDIO_PRESS', 'Photo Studio / Printing Press'), ('CORPORATE_AGENCY', 'Corporate ID Agency'), ('NGO', 'NGO / Non-Profit'), ('OTHER', 'Other Institution')], default='SCHOOL', max_length=30),
        ),
        migrations.CreateModel(
            name='OrganizationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(editable=False, help_text='Unique client code (e.g. CLT-00001)', max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('client_type', models.CharField(choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('TRAINING_INSTITUTE', 'Training Institute'), ('COMPANY', 'Company / Corporate'), ('STUDIO_PRESS', 'Photo Studio / Printing Press'), ('CORPORATE_AGENCY', 'Corporate ID Agency'), ('NGO', 'NGO / Non-Profit'), ('OTHER', 'Other Institution')], default='SCHOOL', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/logos/')),
                ('authorized_signature', models.ImageField(blank=True, null=True, upload_to='clients/signatures/')),
                ('signatory_name', models.CharField(blank=True, default='Principal', max_length=150)),
                ('signatory_title', models.CharField(default='Principal', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='platform_admin.organization')),
                ('school', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to='core.school')),
            ],
            options={
                'verbose_name': 'Organization Client',
                'verbose_name_plural': 'Organization Clients',
                'ordering': ['name'],
            },
        ),
    ]
