# Generated by Django 6.0.7 on 2026-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_subscriptionplan_max_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsetting',
            name='app_description',
            field=models.TextField(blank=True, default='An organization ID-card management and verification application.', verbose_name='Mobile App Description'),
        ),
    ]
