# Generated by Django 6.0.7 on 2026-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0004_alter_platformsetting_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='uses_mobile_app',
            field=models.BooleanField(default=True, help_text='Enable if this organization uses the mobile app for student photo capture and verification.', verbose_name='Uses Mobile App'),
        ),
        migrations.AddField(
            model_name='organizationclient',
            name='uses_mobile_app',
            field=models.BooleanField(default=True, help_text='Enable if this client organization uses the mobile app for student photo capture and verification.', verbose_name='Uses Mobile App'),
        ),
    ]
