# Generated by Django 6.0.7 on 2026-09-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0005_organization_uses_mobile_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2026 CardFlow ID. All Rights Reserved.', max_length=200, verbose_name='Copyright Text'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='developed_by',
            field=models.CharField(blank=True, default='Apex Software Systems', max_length=150, verbose_name='Developed By'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='developed_by_url',
            field=models.URLField(blank=True, default='https://apexid.io', verbose_name='Developer Website URL'),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='platform/branding/', verbose_name='Favicon (.ico, .png)'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='platform_logo',
            field=models.ImageField(blank=True, null=True, upload_to='platform/branding/', verbose_name='Master Platform Logo'),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='platform_name',
            field=models.CharField(default='CardFlow ID', max_length=150, verbose_name='Site / Platform Name'),
        ),
    ]
