# Generated by Django 6.0.7 on 2026-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0006_platformsetting_copyright_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DEMO_REQUEST', 'Demo Request'), ('PACKAGE_ORDER', 'Package Order / Inquiry'), ('NEW_ORGANIZATION', 'New Organization Registered'), ('SUBSCRIPTION_EXPIRING', 'Subscription Expiring Soon'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired'), ('QUOTA_REACHED', 'Quota Limit Exceeded'), ('SECURITY_ALERT', 'Security Alert'), ('SYSTEM', 'System Notification')], db_index=True, default='DEMO_REQUEST', max_length=40)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('sender_name', models.CharField(blank=True, max_length=150)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_phone', models.CharField(blank=True, max_length=50)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('organization_type', models.CharField(blank=True, max_length=50)),
                ('plan_code', models.CharField(blank=True, max_length=50)),
                ('plan_name', models.CharField(blank=True, max_length=100)),
                ('link', models.CharField(blank=True, help_text='Internal URL for quick action', max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Follow-up'), ('CONTACTED', 'Contacted / In Progress'), ('RESOLVED', 'Completed / Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Internal super-admin notes or follow-up status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Notification',
                'verbose_name_plural': 'Platform Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
