# Generated by Django 6.0.7 on 2026-09-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('platform_admin', '0004_alter_platformsetting_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization this academic session belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='platform_admin.organization'),
        ),
        migrations.AddField(
            model_name='classlevel',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization this class level belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='platform_admin.organization'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one academic year should normally be active per organization'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text='e.g. 2026/27', max_length=50),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(help_text='e.g. Grade 1, Grade 8, Kindergarten', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_academic_year_per_org'),
        ),
        migrations.AddConstraint(
            model_name='classlevel',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_class_level_per_org'),
        ),
    ]
