# Generated by Django 6.0.7 on 2026-09-19 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Apex International Academy', max_length=255)),
                ('short_name', models.CharField(default='AIA', max_length=50)),
                ('address', models.CharField(blank=True, default='123 Education Lane', max_length=255)),
                ('municipality', models.CharField(blank=True, default='Kathmandu Metropolitan', max_length=100)),
                ('district', models.CharField(blank=True, default='Kathmandu', max_length=100)),
                ('province', models.CharField(blank=True, default='Bagmati', max_length=100)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('phone', models.CharField(blank=True, default='+977-1-4567890', max_length=50)),
                ('email', models.EmailField(blank=True, default='info@apexschool.edu.np', max_length=254)),
                ('website', models.URLField(blank=True, default='https://apexschool.edu.np')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logo/')),
                ('head_teacher_name', models.CharField(default='Dr. John Doe', max_length=150)),
                ('head_teacher_signature', models.ImageField(blank=True, null=True, upload_to='school/signatures/')),
                ('default_id_validity_days', models.PositiveIntegerField(default=365)),
                ('default_qr_correction_level', models.CharField(choices=[('L', 'L - 7%'), ('M', 'M - 15%'), ('Q', 'Q - 25%'), ('H', 'H - 30%')], default='M', max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADMIN_LOGIN', 'Admin Login'), ('TEACHER_LOGIN', 'Teacher Login'), ('STUDENT_CREATED', 'Student Created'), ('STUDENT_EDITED', 'Student Edited'), ('PHOTO_CHANGED', 'Student Photo Changed'), ('VERIFICATION_SUBMITTED', 'Verification Submitted'), ('STUDENT_APPROVED', 'Student Approved'), ('STUDENT_REJECTED', 'Student Rejected'), ('TEMPLATE_CHANGED', 'Template Changed'), ('PDF_GENERATED', 'PDF Generated'), ('ID_REVOKED', 'ID Card Revoked'), ('SIGNATURE_CHANGED', 'Principal Signature Changed'), ('TEACHER_ASSIGNMENT_CHANGED', 'Teacher Assignment Changed'), ('EXCEL_IMPORT', 'Excel Students Imported'), ('BULK_PHOTOS', 'Bulk Photos Processed')], max_length=60)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
