# Generated by Django 6.0.7 on 2026-09-19 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_type', models.CharField(choices=[('STUDENT', 'Student ID'), ('TEACHER', 'Teacher ID'), ('STAFF', 'Staff ID')], default='STUDENT', max_length=20)),
                ('orientation', models.CharField(choices=[('PORTRAIT', 'Portrait (54 x 86 mm)'), ('LANDSCAPE', 'Landscape (86 x 54 mm)')], default='PORTRAIT', max_length=20)),
                ('width_mm', models.FloatField(default=54.0, help_text='Card width in millimeters (CR80 portrait is 54mm)')),
                ('height_mm', models.FloatField(default=86.0, help_text='Card height in millimeters (CR80 portrait is 86mm)')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Front background hex color', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='templates/backgrounds/')),
                ('back_background_color', models.CharField(default='#F8FAFC', help_text='Back background hex color', max_length=20)),
                ('back_background_image', models.ImageField(blank=True, null=True, upload_to='templates/backgrounds/')),
                ('duplex_mode', models.CharField(choices=[('FRONT_ONLY', 'Front Only'), ('BACK_ONLY', 'Back Only'), ('FRONT_BACK', 'Front & Back')], default='FRONT_BACK', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrintLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard A4 Layout', max_length=100)),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('A3', 'A3 (297 x 420 mm)'), ('LETTER', 'US Letter (215.9 x 279.4 mm)'), ('LEGAL', 'US Legal (215.9 x 355.6 mm)'), ('CUSTOM', 'Custom Dimensions')], default='A4', max_length=20)),
                ('custom_width_mm', models.FloatField(blank=True, help_text='Used only if paper_size is CUSTOM', null=True)),
                ('custom_height_mm', models.FloatField(blank=True, help_text='Used only if paper_size is CUSTOM', null=True)),
                ('orientation', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('LANDSCAPE', 'Landscape')], default='PORTRAIT', max_length=20)),
                ('margin_top_mm', models.FloatField(default=10.0)),
                ('margin_bottom_mm', models.FloatField(default=10.0)),
                ('margin_left_mm', models.FloatField(default=10.0)),
                ('margin_right_mm', models.FloatField(default=10.0)),
                ('gap_x_mm', models.FloatField(default=4.0, help_text='Horizontal spacing between cards')),
                ('gap_y_mm', models.FloatField(default=4.0, help_text='Vertical spacing between cards')),
                ('cols', models.IntegerField(default=3, help_text='Number of columns across sheet')),
                ('rows', models.IntegerField(default=5, help_text='Number of rows down sheet')),
                ('show_crop_marks', models.BooleanField(default=True)),
                ('crop_mark_length_mm', models.FloatField(default=4.0)),
                ('crop_mark_offset_mm', models.FloatField(default=2.0)),
                ('duplex_alignment', models.CharField(choices=[('MIRROR_COLUMNS', 'Mirror Columns (Duplex Back)'), ('SAME_POSITION', 'Same Position')], default='MIRROR_COLUMNS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('secure_token', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('card_status', models.CharField(choices=[('NOT_GENERATED', 'Not Generated'), ('GENERATED', 'Generated'), ('PRINTED', 'Printed')], default='GENERATED', max_length=20)),
                ('validity_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20)),
                ('revocation_reason', models.TextField(blank=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_cards', to='academic.academicyear')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cards', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_cards', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_cards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='students.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_cards', to='idcards.idcardtemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('FRONT', 'Front Side'), ('BACK', 'Back Side')], default='FRONT', max_length=10)),
                ('element_type', models.CharField(choices=[('TEXT', 'Static Text'), ('DYNAMIC_FIELD', 'Dynamic Field'), ('STUDENT_PHOTO', 'Student Photo'), ('SCHOOL_LOGO', 'School Logo'), ('QR_CODE', 'QR Code'), ('SIGNATURE', 'Principal Signature'), ('RECTANGLE', 'Rectangle / Header Card'), ('LINE', 'Divider Line'), ('IMAGE', 'Custom Image')], max_length=30)),
                ('dynamic_field_key', models.CharField(blank=True, help_text='e.g. {{student.name}}, {{student.student_id}}, {{student.roll_no}}, {{student.class}}, {{student.section}}, {{student.dob}}, {{student.gender}}, {{student.address}}, {{student.guardian_name}}, {{school.name}}, {{school.logo}}, {{school.head_teacher_name}}, {{school.head_teacher_signature}}, {{valid_from}}, {{valid_until}}, {{qr_code}}', max_length=100)),
                ('label_text', models.CharField(blank=True, help_text='Static text or element display label', max_length=255)),
                ('x_mm', models.FloatField(default=5.0)),
                ('y_mm', models.FloatField(default=5.0)),
                ('width_mm', models.FloatField(default=44.0)),
                ('height_mm', models.FloatField(default=10.0)),
                ('font_family', models.CharField(default='Helvetica', max_length=50)),
                ('font_size', models.FloatField(default=10.0)),
                ('font_weight', models.CharField(choices=[('NORMAL', 'Normal'), ('BOLD', 'Bold')], default='NORMAL', max_length=20)),
                ('font_color', models.CharField(default='#0F172A', max_length=20)),
                ('text_align', models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], default='LEFT', max_length=20)),
                ('fill_color', models.CharField(blank=True, default='', help_text='Hex color for rectangles', max_length=20)),
                ('border_color', models.CharField(blank=True, default='', max_length=20)),
                ('border_width', models.FloatField(default=0.0)),
                ('border_radius', models.FloatField(default=0.0)),
                ('z_index', models.IntegerField(default=1)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='idcards.idcardtemplate')),
            ],
            options={
                'ordering': ['side', 'z_index', 'id'],
            },
        ),
    ]
