# Generated by Django 6.0.7 on 2026-09-19 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='back_bg_fit_mode',
            field=models.CharField(choices=[('FILL', 'Fill (Exact dimensions)'), ('FIT', 'Fit (Maintain aspect ratio, letterbox)'), ('CROP', 'Crop (Maintain aspect ratio, center-crop)')], default='FILL', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='back_image_dpi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='back_resolution_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='back_resolution_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='bg_fit_mode',
            field=models.CharField(choices=[('FILL', 'Fill (Exact dimensions)'), ('FIT', 'Fit (Maintain aspect ratio, letterbox)'), ('CROP', 'Crop (Maintain aspect ratio, center-crop)')], default='FILL', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='design_mode',
            field=models.CharField(choices=[('SCRATCH', 'Design From Scratch'), ('IMAGE_UPLOAD', 'Upload Existing Design')], default='SCRATCH', max_length=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='front_image_dpi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='front_resolution_h',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='front_resolution_w',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='idcards.idcardtemplate'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='auto_shrink_text',
            field=models.BooleanField(default=True, help_text='Auto-reduce font size if text overflows'),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='font_style',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ITALIC', 'Italic')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='is_circular',
            field=models.BooleanField(default=False, help_text='Circular crop for student photo'),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='opacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='qr_error_correction',
            field=models.CharField(choices=[('L', 'L (7%)'), ('M', 'M (15%)'), ('Q', 'Q (25%)'), ('H', 'H (30%)')], default='M', max_length=5),
        ),
        migrations.AddField(
            model_name='templateelement',
            name='text_wrap',
            field=models.BooleanField(default=False, help_text='Wrap long text lines'),
        ),
        migrations.AlterField(
            model_name='templateelement',
            name='element_type',
            field=models.CharField(choices=[('TEXT', 'Static Text'), ('DYNAMIC_FIELD', 'Dynamic Field'), ('STUDENT_PHOTO', 'Student Photo'), ('SCHOOL_LOGO', 'School Logo'), ('QR_CODE', 'QR Code'), ('SIGNATURE', 'Head Teacher Signature'), ('RECTANGLE', 'Rectangle / Header Card'), ('LINE', 'Divider Line'), ('IMAGE', 'Custom Image')], max_length=30),
        ),
    ]
