# Generated by Django 6.0.7 on 2026-09-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0002_idcardtemplate_back_bg_fit_mode_and_more'),
        ('platform_admin', '0003_subscriptionplan_max_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Associated client school when managed by a Studio / Press account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='platform_admin.organizationclient'),
        ),
    ]
