# Generated by Django 6.0.7 on 2026-09-20 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcards', '0003_idcardtemplate_client'),
        ('platform_admin', '0004_alter_platformsetting_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization this template belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_templates', to='platform_admin.organization'),
        ),
    ]
