# Generated by Django 6.0.7 on 2026-09-20 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('platform_admin', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization/institution this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='platform_admin.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('TEACHER', 'Class Teacher'), ('SUPER_ADMIN', 'Super Admin')], default='ADMIN', max_length=20),
        ),
    ]
