# Generated by Django 6.0.7 on 2026-09-20 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization_alter_user_role'),
        ('platform_admin', '0004_alter_platformsetting_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='client',
            field=models.ForeignKey(blank=True, help_text='For studio/press accounts, the specific client school this teacher belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='platform_admin.organizationclient'),
        ),
    ]
