# Generated by Django 6.0.7 on 2026-09-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_subscriptionplan_max_clients_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Associated client school when managed by a Photo Studio / Printing Press account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='platform_admin.organizationclient'),
        ),
    ]
