# Generated by Django 6.0.7 on 2026-09-20 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicyear_organization_classlevel_organization_and_more'),
        ('platform_admin', '0004_alter_platformsetting_app_description'),
        ('students', '0002_student_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_roll_per_class_section_year',
        ),
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant organization this student record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='platform_admin.organization'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('organization', 'roll_number', 'class_level', 'section', 'academic_year'), name='unique_roll_per_class_section_year_org'),
        ),
    ]
