# Generated by Django 6.0.7 on 2026-09-20 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicyear_organization_classlevel_organization_and_more'),
        ('platform_admin', '0004_alter_platformsetting_app_description'),
        ('students', '0003_remove_student_unique_roll_per_class_section_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_roll_per_class_section_year_org',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True)), fields=('organization', 'roll_number', 'class_level', 'section', 'academic_year'), name='unique_roll_per_class_section_year_org'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('organization', 'client', 'roll_number', 'class_level', 'section', 'academic_year'), name='unique_roll_per_class_section_year_client'),
        ),
    ]
